### PR TITLE
Issues 1 older vim version support

### PR DESCRIPTION
**Pull request by ColinKennedy**
Made to address this issue: https://github.com/ColinKennedy/vim-python-function-expander/issues/1

### CODE REVIEW

**Comment by wookayin** [comment]
Looks good --- works well with neovim.

A question just out of curiosity: if `jedi-vim` is a requirement/dependency of this plugin, then why not `:PythonJedi`?

**Comment by Kazy** [comment]
Works well with Neovim if `let g:jedi#show_call_signatures = 0`. Otherwise the following error happens:

<details><summary>I'm not sure this is related to this PR, let me know if your prefer I open a separate issue for it.</summary>

```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new
Please read and follow:
https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs

Following is the full stack trace:
Traceback (most recent call last):
  File "/home/akear/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
    return func(self, *args, **kwds)
  File "/home/akear/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 138, in expand_or_jump
    rv = self._try_expand()
  File "/home/akear/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 710, in _try_expand
    self._do_snippet(snippet, before)
  File "/home/akear/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 681, in _do_snippet
    self._jump()
  File "/home/akear/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 519, in _jump
    snippet_for_action
  File "/home/akear/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet/definition/_base.py", line 433, in do_post_jump
    self._actions['post_jump'], current_snippet.context, locals
  File "/home/akear/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet/definition/_base.py", line 195, in _execute_action
    snip = self._eval_code(action, locals)
  File "/home/akear/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet/definition/_base.py", line 170, in _eval_code
    exec(code, {'snip': snip})
  File "<string>", line 4, in <module>
  File "/home/akear/.config/nvim/plugged/vim-python-function-expander/pythonx/python_function_expander/jedi_expander.py", line 311, in expand_signatures
    clear_call_signatures(snip)
  File "/home/akear/.config/nvim/plugged/vim-python-function-expander/pythonx/python_function_expander/jedi_expander.py", line 247, in clear_call_signatures
    for i, line in enumerate(snip.buffer):
  File "/home/akear/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/buffer_proxy.py", line 129, in __getitem__
    return as_unicode(self._buffer[key])
  File "/home/akear/.pyenv/versions/neovim3/lib/python3.6/site-packages/neovim/api/buffer.py", line 45, in __getitem__
    return self.request('nvim_buf_get_lines', i, i + 1, True)[0]
  File "/home/akear/.pyenv/versions/neovim3/lib/python3.6/site-packages/neovim/api/common.py", line 44, in request
    return self._session.request(name, self, *args, **kwargs)
  File "/home/akear/.pyenv/versions/neovim3/lib/python3.6/site-packages/neovim/api/nvim.py", line 170, in request
    res = self._session.request(name, *args, **kwargs)
  File "/home/akear/.pyenv/versions/neovim3/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 100, in request
    raise self.error_wrapper(err)
neovim.api.nvim.NvimError: b'Index out of bounds'

Snippet, caused error:

  Defined in: /home/akear/.config/nvim/plugged/vim-python-function-expander/UltiSnips/python.snippets:9
  Trigger: (
  Description: "Expand the current callable object"
  Context: not aide.is_string() and not aide.is_comment()
  Pre-expand: <none>
  Post-expand: <none>

Executed snippet code:
  1   import re, os, vim, string, random
  2   from python_function_expander.ultisnipsaide import ultisnipsaide as aide
  3   from python_function_expander import jedi_expander
  4   jedi_expander.expand_signatures(snip, force=True)
```

The code used to trigger it, with `|` the cursor, and pressing the UltiSnips expand key:
```python
def my_func(foo, bar, baz=None):
    pass

my_func(|)
```

</details>

**Comment by ColinKennedy** [comment]
@wookayin Because the plugin is very close to not needing jedi-vim and I'd like to remove that dependency if I can.

When I first wrote the plugin, `jedi-vim` had a much greater role. Now though, I think the only place I use it is when `g:expander_full_auto` is `1`. If possible, I'd rather just use `jedi` and forgo `vim-jedi` exactly for kinds of unexpected issues it can bring like @Kazy mentioned.

@Kazy If you don't mind making a separate issue, I'd appreciate it. IIRC `snip.buffer` has different behavior in neovim which is the source of the issue

**Comment by Kazy** [comment]
I'll do that ! Thanks for the plugin (and fixing the bug), it's quite useful :)

**Pull request merged**
